# Generated by Django 3.1.1 on 2021-05-29 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='g_images',
            new_name='images',
        ),
    ]
