# Generated by Django 3.1.1 on 2021-05-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210529_2315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryphoto',
            old_name='images',
            new_name='photos',
        ),
    ]
