# Generated by Django 3.2 on 2021-06-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210601_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
