# Generated by Django 3.2 on 2021-07-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_shareexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shareexperience',
            old_name='user',
            new_name='log_user',
        ),
    ]
